apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
spec:
  selector:
    matchLabels:
      app: game
  replicas: 4
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: cloudowski/whackapod-game
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: game-deployment
  labels:
    app: game
spec:
  ports:
  - port: 8080
  selector:
    app: game
